#pragma once
#include <common/Base.hh>

namespace Monoworks::RHI 
{
	/** 
	* @brief Vulkan Compatible Texture Format Enumeration based on VkFormat. Philosophy: put the DirectX in the Vulkan, not the Vulkan in the DirectX.
	* When using DirectX, Setup a translate function to translate it into the DirectX equivalent.
	*/
	enum EImageFormat
	{
		MW_FORMAT_UNDEFINED = 0,
		// RGB8
		MW_FORMAT_R8G8B8_UNORM = 23,
		MW_FORMAT_R8G8B8_SNORM = 24,
		MW_FORMAT_R8G8B8_USCALED = 25,
		MW_FORMAT_R8G8B8_SSCALED = 26,
		MW_FORMAT_R8G8B8_UINT = 27,
		MW_FORMAT_R8G8B8_SINT = 28,
		MW_FORMAT_R8G8B8_SRGB = 29,
		// BGR8
		MW_FORMAT_B8G8R8_UNORM = 30,
		MW_FORMAT_B8G8R8_SNORM = 31,
		MW_FORMAT_B8G8R8_USCALED = 32,
		MW_FORMAT_B8G8R8_SSCALED = 33,
		MW_FORMAT_B8G8R8_UINT = 34,
		MW_FORMAT_B8G8R8_SINT = 35,
		MW_FORMAT_B8G8R8_SRGB = 36,
		// RGBA8 
		MW_FORMAT_R8G8B8A8_UNORM = 37,
		MW_FORMAT_R8G8B8A8_SNORM = 38,
		MW_FORMAT_R8G8B8A8_USCALED = 39,
		MW_FORMAT_R8G8B8A8_SSCALED = 40,
		MW_FORMAT_R8G8B8A8_UINT = 41,
		MW_FORMAT_R8G8B8A8_SINT = 42,
		MW_FORMAT_R8G8B8A8_SRGB = 43,
		// BGRA8
		MW_FORMAT_B8G8R8A8_UNORM = 44,
		MW_FORMAT_B8G8R8A8_SNORM = 45,
		MW_FORMAT_B8G8R8A8_USCALED = 46,
		MW_FORMAT_B8G8R8A8_SSCALED = 47,
		MW_FORMAT_B8G8R8A8_UINT = 48,
		MW_FORMAT_B8G8R8A8_SINT = 49,
		MW_FORMAT_B8G8R8A8_SRGB = 50,
		// R32
		MW_FORMAT_R32_UINT = 98,
		MW_FORMAT_R32_SINT = 99,
		MW_FORMAT_R32_SFLOAT = 100,
	};

	using EImageUsageFlags = u32; // Bitmask, use EImageUsageFlagsBits

	enum EImageUsageFlagsBits
	{
		MW_IMAGE_USAGE_TRANSFER_SRC_BIT = 0x00000001,
		MW_IMAGE_USAGE_TRANSFER_DST_BIT = 0x00000002,
		MW_IMAGE_USAGE_HOST_TRANSFER_BIT = 0x00400000,

		MW_IMAGE_USAGE_SAMPLED_BIT = 0x00000004,

		MW_IMAGE_USAGE_STORAGE_BIT = 0x00000008,

		MW_IMAGE_USAGE_COLOR_ATTACHMENT_BIT = 0x00000010,
		MW_IMAGE_USAGE_DEPTH_STENCIL_ATTACHMENT_BIT = 0x00000020,
		MW_IMAGE_USAGE_TRANSIENT_ATTACHMENT_BIT = 0x00000040,
		MW_IMAGE_USAGE_INPUT_ATTACHMENT_BIT = 0x00000080,
		MW_IMAGE_USAGE_FRAGMENT_SHADING_RATE_ATTACHMENT_BIT_KHR = 0x00000100,

		MW_IMAGE_USAGE_VIDEO_DECODE_DST_BIT_KHR = 0x00000400,
		MW_IMAGE_USAGE_VIDEO_DECODE_SRC_BIT_KHR = 0x00000800,
		MW_IMAGE_USAGE_VIDEO_DECODE_DPB_BIT_KHR = 0x00001000,

		MW_IMAGE_USAGE_FRAGMENT_DENSITY_MAP_BIT_EXT = 0x00000200,

		MW_IMAGE_USAGE_VIDEO_ENCODE_DST_BIT_KHR = 0x00002000,
		MW_IMAGE_USAGE_VIDEO_ENCODE_SRC_BIT_KHR = 0x00004000,
		MW_IMAGE_USAGE_VIDEO_ENCODE_DPB_BIT_KHR = 0x00008000,
		MW_IMAGE_USAGE_VIDEO_ENCODE_QUANTIZATION_DELTA_MAP_BIT_KHR = 0x02000000,
		MW_IMAGE_USAGE_VIDEO_ENCODE_EMPHASIS_MAP_BIT_KHR = 0x04000000,

		MW_IMAGE_USAGE_ATTACHMENT_FEEDBACK_LOOP_BIT_EXT = 0x00080000,

		MW_IMAGE_USAGE_FLAG_BITS_MAX_ENUM = 0x7FFFFFFF
	};

	enum EImageLayout
	{
		MW_IMAGE_LAYOUT_UNDEFINED = 0,

		MW_IMAGE_LAYOUT_GENERAL = 1,
		MW_IMAGE_LAYOUT_PREINITIALIZED = 8,

		// Attachments
		MW_IMAGE_LAYOUT_ATTACHMENT_OPTIMAL = 1000314001,
		MW_IMAGE_LAYOUT_COLOR_ATTACHMENT_OPTIMAL = 2,
		MW_IMAGE_LAYOUT_DEPTH_STENCIL_ATTACHMENT_OPTIMAL = 3,
		MW_IMAGE_LAYOUT_DEPTH_ATTACHMENT_STENCIL_READ_ONLY_OPTIMAL = 1000117001,
		MW_IMAGE_LAYOUT_DEPTH_ATTACHMENT_OPTIMAL = 1000241000,
		MW_IMAGE_LAYOUT_DEPTH_READ_ONLY_STENCIL_ATTACHMENT_OPTIMAL = 1000117000,
		MW_IMAGE_LAYOUT_STENCIL_ATTACHMENT_OPTIMAL = 1000241002,

		// Read Only
		MW_IMAGE_LAYOUT_READ_ONLY_OPTIMAL = 1000314000,
		MW_IMAGE_LAYOUT_DEPTH_STENCIL_READ_ONLY_OPTIMAL = 4,
		MW_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL = 5,
		MW_IMAGE_LAYOUT_DEPTH_READ_ONLY_OPTIMAL = 1000241001,
		MW_IMAGE_LAYOUT_STENCIL_READ_ONLY_OPTIMAL = 1000241003,

		// Transfer
		MW_IMAGE_LAYOUT_TRANSFER_SRC_OPTIMAL = 6,
		MW_IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL = 7,

		MW_IMAGE_LAYOUT_RENDERING_LOCAL_READ = 1000232000,

		// Present
		MW_IMAGE_LAYOUT_PRESENT_SRC_KHR = 1000001002,
		MW_IMAGE_LAYOUT_SHARED_PRESENT_KHR = 1000111000,

		MW_IMAGE_LAYOUT_VIDEO_DECODE_DST_KHR = 1000024000,
		MW_IMAGE_LAYOUT_VIDEO_DECODE_SRC_KHR = 1000024001,
		MW_IMAGE_LAYOUT_VIDEO_DECODE_DPB_KHR = 1000024002,

		MW_IMAGE_LAYOUT_FRAGMENT_DENSITY_MAP_OPTIMAL_EXT = 1000218000,
		MW_IMAGE_LAYOUT_FRAGMENT_SHADING_RATE_ATTACHMENT_OPTIMAL_KHR = 1000164003,

		MW_IMAGE_LAYOUT_VIDEO_ENCODE_DST_KHR = 1000299000,
		MW_IMAGE_LAYOUT_VIDEO_ENCODE_SRC_KHR = 1000299001,
		MW_IMAGE_LAYOUT_VIDEO_ENCODE_DPB_KHR = 1000299002,

		MW_IMAGE_LAYOUT_ATTACHMENT_FEEDBACK_LOOP_OPTIMAL_EXT = 1000339000,

		MW_IMAGE_LAYOUT_TENSOR_ALIASING_ARM = 1000460000,

		MW_IMAGE_LAYOUT_VIDEO_ENCODE_QUANTIZATION_MAP_KHR = 1000553000,

		MW_IMAGE_LAYOUT_ZERO_INITIALIZED_EXT = 1000620000,

		MW_IMAGE_LAYOUT_MAX_ENUM = 0x7FFFFFFF
	};

	using EImageAspectFlags = u32; // Bitmask, use EImageAspectFlagBits

	enum EImageAspectFlagBits
	{
		MW_IMAGE_ASPECT_NONE = 0,
		MW_IMAGE_ASPECT_COLOR_BIT = 0x00000001,
		MW_IMAGE_ASPECT_DEPTH_BIT = 0x00000002,
		MW_IMAGE_ASPECT_STENCIL_BIT = 0x00000004,

		MW_IMAGE_ASPECT_METADATA_BIT = 0x00000008,

		MW_IMAGE_ASPECT_PLANE_0_BIT = 0x00000010,
		MW_IMAGE_ASPECT_PLANE_1_BIT = 0x00000020,
		MW_IMAGE_ASPECT_PLANE_2_BIT = 0x00000040,

		MW_IMAGE_ASPECT_MEMORY_PLANE_0_BIT_EXT = 0x00000080,
		MW_IMAGE_ASPECT_MEMORY_PLANE_1_BIT_EXT = 0x00000100,
		MW_IMAGE_ASPECT_MEMORY_PLANE_2_BIT_EXT = 0x00000200,
		MW_IMAGE_ASPECT_MEMORY_PLANE_3_BIT_EXT = 0x00000400,

		MW_IMAGE_ASPECT_FLAG_BITS_MAX_ENUM = 0x7FFFFFFF
	};

	using EPipelineFlags = u32; // Bitmask, use EPipelineFlagBits

	enum EPipelineFlagBits
	{
		MW_PIPELINE_STAGE_TOP_OF_PIPE_BIT = 0x00000001,
		MW_PIPELINE_STAGE_DRAW_INDIRECT_BIT = 0x00000002,
		MW_PIPELINE_STAGE_VERTEX_INPUT_BIT = 0x00000004,
		MW_PIPELINE_STAGE_VERTEX_SHADER_BIT = 0x00000008,
		MW_PIPELINE_STAGE_TESSELLATION_CONTROL_SHADER_BIT = 0x00000010,
		MW_PIPELINE_STAGE_TESSELLATION_EVALUATION_SHADER_BIT = 0x00000020,
		MW_PIPELINE_STAGE_GEOMETRY_SHADER_BIT = 0x00000040,
		MW_PIPELINE_STAGE_FRAGMENT_SHADER_BIT = 0x00000080,
		MW_PIPELINE_STAGE_EARLY_FRAGMENT_TESTS_BIT = 0x00000100,
		MW_PIPELINE_STAGE_LATE_FRAGMENT_TESTS_BIT = 0x00000200,
		MW_PIPELINE_STAGE_COLOR_ATTACHMENT_OUTPUT_BIT = 0x00000400,
		MW_PIPELINE_STAGE_COMPUTE_SHADER_BIT = 0x00000800,
		MW_PIPELINE_STAGE_TRANSFER_BIT = 0x00001000,
		MW_PIPELINE_STAGE_BOTTOM_OF_PIPE_BIT = 0x00002000,
		MW_PIPELINE_STAGE_HOST_BIT = 0x00004000,
		MW_PIPELINE_STAGE_ALL_GRAPHICS_BIT = 0x00008000,
		MW_PIPELINE_STAGE_ALL_COMMANDS_BIT = 0x00010000,
		MW_PIPELINE_STAGE_NONE = 0,
		MW_PIPELINE_STAGE_TRANSFORM_FEEDBACK_BIT_EXT = 0x01000000,
		MW_PIPELINE_STAGE_CONDITIONAL_RENDERING_BIT_EXT = 0x00040000,
		MW_PIPELINE_STAGE_ACCELERATION_STRUCTURE_BUILD_BIT_KHR = 0x02000000,
		MW_PIPELINE_STAGE_RAY_TRACING_SHADER_BIT_KHR = 0x00200000,
		MW_PIPELINE_STAGE_FRAGMENT_DENSITY_PROCESS_BIT_EXT = 0x00800000,
		MW_PIPELINE_STAGE_FRAGMENT_SHADING_RATE_ATTACHMENT_BIT_KHR = 0x00400000,
		MW_PIPELINE_STAGE_TASK_SHADER_BIT_EXT = 0x00080000,
		MW_PIPELINE_STAGE_MESH_SHADER_BIT_EXT = 0x00100000,
		MW_PIPELINE_STAGE_COMMAND_PREPROCESS_BIT_EXT = 0x00020000,
		MW_PIPELINE_STAGE_FLAG_BITS_MAX_ENUM = 0x7FFFFFFF
	};

	static void TransitionImageLayout2(
		VkCommandBuffer commandBuffer,
		VkImage image,
		VkImageLayout oldLayout,
		VkImageLayout newLayout,
		VkPipelineStageFlags srcStageMask,
		VkPipelineStageFlags dstStageMask )
	{
		VkImageMemoryBarrier barrier{};
		barrier.sType = VK_STRUCTURE_TYPE_IMAGE_MEMORY_BARRIER;
		barrier.oldLayout = oldLayout;
		barrier.newLayout = newLayout;
		barrier.srcQueueFamilyIndex = VK_QUEUE_FAMILY_IGNORED;
		barrier.dstQueueFamilyIndex = VK_QUEUE_FAMILY_IGNORED;
		barrier.image = image;
		barrier.subresourceRange.aspectMask = VK_IMAGE_ASPECT_COLOR_BIT;
		barrier.subresourceRange.baseMipLevel = 0;
		barrier.subresourceRange.levelCount = 1;
		barrier.subresourceRange.baseArrayLayer = 0;
		barrier.subresourceRange.layerCount = 1;

		if ( oldLayout == VK_IMAGE_LAYOUT_COLOR_ATTACHMENT_OPTIMAL &&
			newLayout == VK_IMAGE_LAYOUT_PRESENT_SRC_KHR )
		{
			barrier.srcAccessMask = VK_ACCESS_COLOR_ATTACHMENT_WRITE_BIT;
			barrier.dstAccessMask = 0;
		}
		else if ( oldLayout == VK_IMAGE_LAYOUT_UNDEFINED &&
			newLayout == VK_IMAGE_LAYOUT_COLOR_ATTACHMENT_OPTIMAL )
		{
			barrier.srcAccessMask = 0;
			barrier.dstAccessMask = VK_ACCESS_COLOR_ATTACHMENT_WRITE_BIT;
		}
		else if ( oldLayout == VK_IMAGE_LAYOUT_PRESENT_SRC_KHR &&
			newLayout == VK_IMAGE_LAYOUT_COLOR_ATTACHMENT_OPTIMAL )
		{
			barrier.srcAccessMask = 0;
			barrier.dstAccessMask = VK_ACCESS_COLOR_ATTACHMENT_WRITE_BIT;
		}
		else if ( oldLayout == VK_IMAGE_LAYOUT_UNDEFINED &&
			newLayout == VK_IMAGE_LAYOUT_DEPTH_ATTACHMENT_OPTIMAL )
		{
			barrier.srcAccessMask = 0;
			barrier.dstAccessMask = VK_ACCESS_DEPTH_STENCIL_ATTACHMENT_WRITE_BIT | VK_ACCESS_DEPTH_STENCIL_ATTACHMENT_READ_BIT;
			barrier.subresourceRange.aspectMask = VK_IMAGE_ASPECT_DEPTH_BIT;
		}
		else if ( oldLayout == VK_IMAGE_LAYOUT_UNDEFINED &&
			newLayout == VK_IMAGE_LAYOUT_TRANSFER_SRC_OPTIMAL )
		{
			barrier.srcAccessMask = 0;
			barrier.dstAccessMask = VK_ACCESS_TRANSFER_READ_BIT;
		}
		else if ( oldLayout == VK_IMAGE_LAYOUT_TRANSFER_SRC_OPTIMAL &&
			newLayout == VK_IMAGE_LAYOUT_UNDEFINED )
		{
			barrier.srcAccessMask = VK_ACCESS_TRANSFER_READ_BIT;
			barrier.dstAccessMask = 0;
		}
		else if ( oldLayout == VK_IMAGE_LAYOUT_COLOR_ATTACHMENT_OPTIMAL &&
			newLayout == VK_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL )
		{
			barrier.srcAccessMask = VK_ACCESS_COLOR_ATTACHMENT_WRITE_BIT;
			barrier.dstAccessMask = VK_ACCESS_SHADER_READ_BIT;
		}
		else if ( oldLayout == VK_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL &&
			newLayout == VK_IMAGE_LAYOUT_COLOR_ATTACHMENT_OPTIMAL )
		{
			barrier.srcAccessMask = VK_ACCESS_SHADER_READ_BIT;
			barrier.dstAccessMask = VK_ACCESS_COLOR_ATTACHMENT_WRITE_BIT;
		}
		else if ( oldLayout == VK_IMAGE_LAYOUT_DEPTH_ATTACHMENT_OPTIMAL &&
			newLayout == VK_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL )
		{
			barrier.srcAccessMask = VK_ACCESS_DEPTH_STENCIL_ATTACHMENT_WRITE_BIT;
			barrier.dstAccessMask = VK_ACCESS_SHADER_READ_BIT;
			barrier.subresourceRange.aspectMask = VK_IMAGE_ASPECT_DEPTH_BIT;
		}
		else if ( oldLayout == VK_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL &&
			newLayout == VK_IMAGE_LAYOUT_DEPTH_ATTACHMENT_OPTIMAL )
		{
			barrier.srcAccessMask = VK_ACCESS_SHADER_READ_BIT;
			barrier.dstAccessMask = VK_ACCESS_DEPTH_STENCIL_ATTACHMENT_WRITE_BIT | VK_ACCESS_DEPTH_STENCIL_ATTACHMENT_READ_BIT;
			barrier.subresourceRange.aspectMask = VK_IMAGE_ASPECT_DEPTH_BIT;
		}
		else if ( oldLayout == VK_IMAGE_LAYOUT_COLOR_ATTACHMENT_OPTIMAL &&
			newLayout == VK_IMAGE_LAYOUT_TRANSFER_SRC_OPTIMAL )
		{
			barrier.srcAccessMask = VK_ACCESS_COLOR_ATTACHMENT_WRITE_BIT;
			barrier.dstAccessMask = VK_ACCESS_TRANSFER_READ_BIT;
		}
		else if ( oldLayout == VK_IMAGE_LAYOUT_TRANSFER_SRC_OPTIMAL &&
			newLayout == VK_IMAGE_LAYOUT_COLOR_ATTACHMENT_OPTIMAL )
		{
			barrier.srcAccessMask = VK_ACCESS_TRANSFER_READ_BIT;
			barrier.dstAccessMask = VK_ACCESS_COLOR_ATTACHMENT_WRITE_BIT;
		}
		else if ( oldLayout == VK_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL &&
			newLayout == VK_IMAGE_LAYOUT_TRANSFER_SRC_OPTIMAL )
		{
			barrier.srcAccessMask = VK_ACCESS_SHADER_READ_BIT;
			barrier.dstAccessMask = VK_ACCESS_TRANSFER_READ_BIT;
		}
		else if ( oldLayout == VK_IMAGE_LAYOUT_TRANSFER_SRC_OPTIMAL &&
			newLayout == VK_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL )
		{
			barrier.srcAccessMask = VK_ACCESS_TRANSFER_READ_BIT;
			barrier.dstAccessMask = VK_ACCESS_SHADER_READ_BIT;
		}
		else
		{
			MW_ASSERT( false, "Unsupported layout transition" );
		}

		vkCmdPipelineBarrier(
			commandBuffer,
			srcStageMask,
			dstStageMask,
			0,
			0, nullptr,
			0, nullptr,
			1, &barrier
		);
	}

	static void TransitionImageLayout(
		VkCommandBuffer* pCmdBuffer,
		VkImage* pImage,
		EImageFormat format,
		EImageLayout oldLayout,
		EImageLayout newLayout,
		EImageAspectFlags aspectMask = VK_IMAGE_ASPECT_COLOR_BIT
	)
	{
		VkImageMemoryBarrier barrier{};
		barrier.sType = VK_STRUCTURE_TYPE_IMAGE_MEMORY_BARRIER;
		barrier.oldLayout = ( VkImageLayout )oldLayout;
		barrier.newLayout = ( VkImageLayout )newLayout;
		barrier.srcQueueFamilyIndex = VK_QUEUE_FAMILY_IGNORED;
		barrier.dstQueueFamilyIndex = VK_QUEUE_FAMILY_IGNORED;
		barrier.image = *pImage;
		barrier.subresourceRange.aspectMask = aspectMask;
		barrier.subresourceRange.baseMipLevel = 0;
		barrier.subresourceRange.levelCount = 1;
		barrier.subresourceRange.baseArrayLayer = 0;
		barrier.subresourceRange.layerCount = 1;

		VkPipelineStageFlags sourceStage{};
		VkPipelineStageFlags destinationStage{};

		if ( oldLayout == VK_IMAGE_LAYOUT_UNDEFINED && newLayout == VK_IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL ) {
			barrier.srcAccessMask = 0;
			barrier.dstAccessMask = VK_ACCESS_TRANSFER_WRITE_BIT;

			sourceStage = VK_PIPELINE_STAGE_TOP_OF_PIPE_BIT;
			destinationStage = VK_PIPELINE_STAGE_TRANSFER_BIT;
		}
		else if ( oldLayout == VK_IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL && newLayout == VK_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL ) {
			barrier.srcAccessMask = VK_ACCESS_TRANSFER_WRITE_BIT;
			barrier.dstAccessMask = VK_ACCESS_SHADER_READ_BIT;

			sourceStage = VK_PIPELINE_STAGE_TRANSFER_BIT;
			destinationStage = VK_PIPELINE_STAGE_FRAGMENT_SHADER_BIT;
		}
		else if ( oldLayout == VK_IMAGE_LAYOUT_UNDEFINED && newLayout == VK_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL ) {
			barrier.srcAccessMask = 0;
			barrier.dstAccessMask = VK_ACCESS_SHADER_READ_BIT;

			sourceStage = VK_PIPELINE_STAGE_TOP_OF_PIPE_BIT;
			destinationStage = VK_PIPELINE_STAGE_FRAGMENT_SHADER_BIT;
		}
		else {
			MW_ASSERT( false, "Unsupported layout transition" );
		}

		vkCmdPipelineBarrier(
			*pCmdBuffer,
			sourceStage,
			destinationStage,
			0,
			0, nullptr,
			0, nullptr,
			1, &barrier
		);
	}



}
