/**
 * @defgroup Common Common
 * @brief Common Components shared between every Application
 */
 

/**
 * @file Base.hh
 * @author Theo Wimber (theowimber@abeams.app)
 * @brief Common definitions for the entire engine
 * @version 0.1
 * @date 2026-07-03
 * @ingroup Common
 * @copyright Copyright (c) 2026
 * 
 */

#pragma once
#include <cstdint>
#include <common/Log.h>
#include <core/CVarManager.hh>

#ifdef MW_PROFILING
#include <Tracy/Tracy.hpp>

#define MW_PROFILE_FUNC() ZoneScopedN(__FUNCTION__);
#define MW_PROFILE_FRAME_MARK() FrameMark;

#endif
using cvar_t = Monoworks::SCVar;

#define MW_REG_CVAR(var) Monoworks::CCvarManager::RegisterVariable(var);
#define MW_SET_CVAR(varName, value) Monoworks::CCvarManager::Set(varName, value);
#define MW_SET_FLOAT_CVAR(varName, value) Monoworks::CCvarManager::SetValue(varName, value);

using u8 = uint8_t;
using u16 = uint16_t;
using u32 = uint32_t;
using u64 = uint64_t;

using s8  = int8_t;
using s16 = int16_t;
using s32 = int32_t;
using s64 = int64_t;

using f32 = float;
using f64 = double;

using uptr_t = uintptr_t;
using byte_t = unsigned char;

namespace Monoworks
{
    enum EGraphicsAPI
    {
        MW_GAPI_NONE = 0x0,
        MW_GAPI_VULKAN = 0x10000000
    };

    /**
     * @brief Two-Dimensional Extent Structure
     */
    struct SExtent2D
    {
        /**
         * @brief Height component of the Two-Dimensional Extent.
         */
        u32 Height = 0;

        /**
         * @brief Width component of the Two-Dimensional Extent.
         */
        u32 Width = 0;
    };


    /*
       Copyright (C) 1997-2026 Sam Lantinga <slouken@libsdl.org>

        This software is provided 'as-is', without any express or implied
        warranty.  In no event will the authors be held liable for any damages
        arising from the use of this software.

        Permission is granted to anyone to use this software for any purpose,
        including commercial applications, and to alter it and redistribute it
        freely, subject to the following restrictions:

        1. The origin of this software must not be misrepresented; you must not
           claim that you wrote the original software. If you use this software
           in a product, an acknowledgment in the product documentation would be
           appreciated but is not required.
        2. Altered source versions must be plainly marked as such, and must not be
           misrepresented as being the original software.
        3. This notice may not be removed or altered from any source distribution.

        Modified Scancode implementation by libsdl-org
    */
    enum Scancode 
    {
		MW_SCANCODE_UNKNOWN = 0,
		MW_SCANCODE_A = 4,
		MW_SCANCODE_B = 5,
		MW_SCANCODE_C = 6,
		MW_SCANCODE_D = 7,
		MW_SCANCODE_E = 8,
		MW_SCANCODE_F = 9,
		MW_SCANCODE_G = 10,
		MW_SCANCODE_H = 11,
		MW_SCANCODE_I = 12,
		MW_SCANCODE_J = 13,
		MW_SCANCODE_K = 14,
		MW_SCANCODE_L = 15,
		MW_SCANCODE_M = 16,
		MW_SCANCODE_N = 17,
		MW_SCANCODE_O = 18,
		MW_SCANCODE_P = 19,
		MW_SCANCODE_Q = 20,
		MW_SCANCODE_R = 21,
		MW_SCANCODE_S = 22,
		MW_SCANCODE_T = 23,
		MW_SCANCODE_U = 24,
		MW_SCANCODE_V = 25,
		MW_SCANCODE_W = 26,
		MW_SCANCODE_X = 27,
		MW_SCANCODE_Y = 28,
		MW_SCANCODE_Z = 29,
		MW_SCANCODE_1 = 30,
		MW_SCANCODE_2 = 31,
		MW_SCANCODE_3 = 32,
		MW_SCANCODE_4 = 33,
		MW_SCANCODE_5 = 34,
		MW_SCANCODE_6 = 35,
		MW_SCANCODE_7 = 36,
		MW_SCANCODE_8 = 37,
		MW_SCANCODE_9 = 38,
		MW_SCANCODE_0 = 39,
		MW_SCANCODE_RETURN = 40,
		MW_SCANCODE_ESCAPE = 41,
		MW_SCANCODE_BACKSPACE = 42,
		MW_SCANCODE_TAB = 43,
		MW_SCANCODE_SPACE = 44,
		MW_SCANCODE_MINUS = 45,
		MW_SCANCODE_EQUALS = 46,
		MW_SCANCODE_LEFTBRACKET = 47,
		MW_SCANCODE_RIGHTBRACKET = 48,
		MW_SCANCODE_BACKSLASH = 49,
		MW_SCANCODE_NONUSHASH = 50,
		MW_SCANCODE_SEMICOLON = 51,
		MW_SCANCODE_APOSTROPHE = 52,
		MW_SCANCODE_GRAVE = 53,
		MW_SCANCODE_COMMA = 54,
		MW_SCANCODE_PERIOD = 55,
		MW_SCANCODE_SLASH = 56,
		MW_SCANCODE_CAPSLOCK = 57,
		MW_SCANCODE_F1 = 58,
		MW_SCANCODE_F2 = 59,
		MW_SCANCODE_F3 = 60,
		MW_SCANCODE_F4 = 61,
		MW_SCANCODE_F5 = 62,
		MW_SCANCODE_F6 = 63,
		MW_SCANCODE_F7 = 64,
		MW_SCANCODE_F8 = 65,
		MW_SCANCODE_F9 = 66,
		MW_SCANCODE_F10 = 67,
		MW_SCANCODE_F11 = 68,
		MW_SCANCODE_F12 = 69,
		MW_SCANCODE_PRINTSCREEN = 70,
		MW_SCANCODE_SCROLLLOCK = 71,
		MW_SCANCODE_PAUSE = 72,
		MW_SCANCODE_INSERT = 73,
		MW_SCANCODE_HOME = 74,
		MW_SCANCODE_PAGEUP = 75,
		MW_SCANCODE_DELETE = 76,
		MW_SCANCODE_END = 77,
		MW_SCANCODE_PAGEDOWN = 78,
		MW_SCANCODE_RIGHT = 79,
		MW_SCANCODE_LEFT = 80,
		MW_SCANCODE_DOWN = 81,
		MW_SCANCODE_UP = 82,
		MW_SCANCODE_NUMLOCKCLEAR = 83,
		MW_SCANCODE_KP_DIVIDE = 84,
		MW_SCANCODE_KP_MULTIPLY = 85,
		MW_SCANCODE_KP_MINUS = 86,
		MW_SCANCODE_KP_PLUS = 87,
		MW_SCANCODE_KP_ENTER = 88,
		MW_SCANCODE_KP_1 = 89,
		MW_SCANCODE_KP_2 = 90,
		MW_SCANCODE_KP_3 = 91,
		MW_SCANCODE_KP_4 = 92,
		MW_SCANCODE_KP_5 = 93,
		MW_SCANCODE_KP_6 = 94,
		MW_SCANCODE_KP_7 = 95,
		MW_SCANCODE_KP_8 = 96,
		MW_SCANCODE_KP_9 = 97,
		MW_SCANCODE_KP_0 = 98,
		MW_SCANCODE_KP_PERIOD = 99,
		MW_SCANCODE_NONUSBACKSLASH = 100,
		MW_SCANCODE_APPLICATION = 101,
		MW_SCANCODE_POWER = 102,
		MW_SCANCODE_KP_EQUALS = 103,
		MW_SCANCODE_F13 = 104,
		MW_SCANCODE_F14 = 105,
		MW_SCANCODE_F15 = 106,
		MW_SCANCODE_F16 = 107,
		MW_SCANCODE_F17 = 108,
		MW_SCANCODE_F18 = 109,
		MW_SCANCODE_F19 = 110,
		MW_SCANCODE_F20 = 111,
		MW_SCANCODE_F21 = 112,
		MW_SCANCODE_F22 = 113,
		MW_SCANCODE_F23 = 114,
		MW_SCANCODE_F24 = 115,
		MW_SCANCODE_EXECUTE = 116,
		MW_SCANCODE_HELP = 117,
		MW_SCANCODE_MENU = 118,
		MW_SCANCODE_SELECT = 119,
		MW_SCANCODE_STOP = 120,
		MW_SCANCODE_AGAIN = 121,
		MW_SCANCODE_UNDO = 122,
		MW_SCANCODE_CUT = 123,
		MW_SCANCODE_COPY = 124,
		MW_SCANCODE_PASTE = 125,
		MW_SCANCODE_FIND = 126,
		MW_SCANCODE_MUTE = 127,
		MW_SCANCODE_VOLUMEUP = 128,
		MW_SCANCODE_VOLUMEDOWN = 129,
		MW_SCANCODE_KP_COMMA = 133,
		MW_SCANCODE_KP_EQUALSAS400 = 134,
		MW_SCANCODE_INTERNATIONAL1 = 135,
		MW_SCANCODE_INTERNATIONAL2 = 136,
		MW_SCANCODE_INTERNATIONAL3 = 137,
		MW_SCANCODE_INTERNATIONAL4 = 138,
		MW_SCANCODE_INTERNATIONAL5 = 139,
		MW_SCANCODE_INTERNATIONAL6 = 140,
		MW_SCANCODE_INTERNATIONAL7 = 141,
		MW_SCANCODE_INTERNATIONAL8 = 142,
		MW_SCANCODE_INTERNATIONAL9 = 143,
		MW_SCANCODE_LANG1 = 144,
		MW_SCANCODE_LANG2 = 145,
		MW_SCANCODE_LANG3 = 146,
		MW_SCANCODE_LANG4 = 147,
		MW_SCANCODE_LANG5 = 148,
		MW_SCANCODE_LANG6 = 149,
		MW_SCANCODE_LANG7 = 150,
		MW_SCANCODE_LANG8 = 151,
		MW_SCANCODE_LANG9 = 152,
		MW_SCANCODE_ALTERASE = 153,
		MW_SCANCODE_SYSREQ = 154,
		MW_SCANCODE_CANCEL = 155,
		MW_SCANCODE_CLEAR = 156,
		MW_SCANCODE_PRIOR = 157,
		MW_SCANCODE_RETURN2 = 158,
		MW_SCANCODE_SEPARATOR = 159,
		MW_SCANCODE_OUT = 160,
		MW_SCANCODE_OPER = 161,
		MW_SCANCODE_CLEARAGAIN = 162,
		MW_SCANCODE_CRSEL = 163,
		MW_SCANCODE_EXSEL = 164,
		MW_SCANCODE_KP_00 = 176,
		MW_SCANCODE_KP_000 = 177,
		MW_SCANCODE_THOUSANDSSEPARATOR = 178,
		MW_SCANCODE_DECIMALSEPARATOR = 179,
		MW_SCANCODE_CURRENCYUNIT = 180,
		MW_SCANCODE_CURRENCYSUBUNIT = 181,
		MW_SCANCODE_KP_LEFTPAREN = 182,
		MW_SCANCODE_KP_RIGHTPAREN = 183,
		MW_SCANCODE_KP_LEFTBRACE = 184,
		MW_SCANCODE_KP_RIGHTBRACE = 185,
		MW_SCANCODE_KP_TAB = 186,
		MW_SCANCODE_KP_BACKSPACE = 187,
		MW_SCANCODE_KP_A = 188,
		MW_SCANCODE_KP_B = 189,
		MW_SCANCODE_KP_C = 190,
		MW_SCANCODE_KP_D = 191,
		MW_SCANCODE_KP_E = 192,
		MW_SCANCODE_KP_F = 193,
		MW_SCANCODE_KP_XOR = 194,
		MW_SCANCODE_KP_POWER = 195,
		MW_SCANCODE_KP_PERCENT = 196,
		MW_SCANCODE_KP_LESS = 197,
		MW_SCANCODE_KP_GREATER = 198,
		MW_SCANCODE_KP_AMPERSAND = 199,
		MW_SCANCODE_KP_DBLAMPERSAND = 200,
		MW_SCANCODE_KP_VERTICALBAR = 201,
		MW_SCANCODE_KP_DBLVERTICALBAR = 202,
		MW_SCANCODE_KP_COLON = 203,
		MW_SCANCODE_KP_HASH = 204,
		MW_SCANCODE_KP_SPACE = 205,
		MW_SCANCODE_KP_AT = 206,
		MW_SCANCODE_KP_EXCLAM = 207,
		MW_SCANCODE_KP_MEMSTORE = 208,
		MW_SCANCODE_KP_MEMRECALL = 209,
		MW_SCANCODE_KP_MEMCLEAR = 210,
		MW_SCANCODE_KP_MEMADD = 211,
		MW_SCANCODE_KP_MEMSUBTRACT = 212,
		MW_SCANCODE_KP_MEMMULTIPLY = 213,
		MW_SCANCODE_KP_MEMDIVIDE = 214,
		MW_SCANCODE_KP_PLUSMINUS = 215,
		MW_SCANCODE_KP_CLEAR = 216,
		MW_SCANCODE_KP_CLEARENTRY = 217,
		MW_SCANCODE_KP_BINARY = 218,
		MW_SCANCODE_KP_OCTAL = 219,
		MW_SCANCODE_KP_DECIMAL = 220,
		MW_SCANCODE_KP_HEXADECIMAL = 221,
		MW_SCANCODE_LCTRL = 224,
		MW_SCANCODE_LSHIFT = 225,
		MW_SCANCODE_LALT = 226,
		MW_SCANCODE_LGUI = 227,
		MW_SCANCODE_RCTRL = 228,
		MW_SCANCODE_RSHIFT = 229,
		MW_SCANCODE_RALT = 230,
		MW_SCANCODE_RGUI = 231,
		MW_SCANCODE_MODE = 257,
		MW_SCANCODE_AUDIONEXT = 258,
		MW_SCANCODE_AUDIOPREV = 259,
		MW_SCANCODE_AUDIOSTOP = 260,
		MW_SCANCODE_AUDIOPLAY = 261,
		MW_SCANCODE_AUDIOMUTE = 262,
		MW_SCANCODE_MEDIASELECT = 263,
		MW_SCANCODE_WWW = 264,
		MW_SCANCODE_MAIL = 265,
		MW_SCANCODE_CALCULATOR = 266,
		MW_SCANCODE_COMPUTER = 267,
		MW_SCANCODE_AC_SEARCH = 268,
		MW_SCANCODE_AC_HOME = 269,
		MW_SCANCODE_AC_BACK = 270,
		MW_SCANCODE_AC_FORWARD = 271,
		MW_SCANCODE_AC_STOP = 272,
		MW_SCANCODE_AC_REFRESH = 273,
		MW_SCANCODE_AC_BOOKMARKS = 274,
		MW_SCANCODE_BRIGHTNESSDOWN = 275,
		MW_SCANCODE_BRIGHTNESSUP = 276,
		MW_SCANCODE_DISPLAYSWITCH = 277,
		MW_SCANCODE_KBDILLUMTOGGLE = 278,
		MW_SCANCODE_KBDILLUMDOWN = 279,
		MW_SCANCODE_KBDILLUMUP = 280,
		MW_SCANCODE_EJECT = 281,
		MW_SCANCODE_SLEEP = 282,
		MW_SCANCODE_APP1 = 283,
		MW_SCANCODE_APP2 = 284,
		MW_SCANCODE_AUDIOREWIND = 285,
		MW_SCANCODE_AUDIOFASTFORWARD = 286,
		MW_SCANCODE_SOFTLEFT = 287,
		MW_SCANCODE_SOFTRIGHT = 288,
		MW_SCANCODE_CALL = 289,
		MW_SCANCODE_ENDCALL = 290,
		MW_NUM_SCANCODES
	};

	enum Mousebutton : u8
	{
		MW_MOUSE_L_BUTTON,
		MW_MOUSE_M_BUTTON,
		MW_MOUSE_R_BUTTON,
		MW_NOUSE_4_BUTTON,
		MW_MOUSE_5_BUTTON
	};

}
